### ISSUE TITLE
cannot import name RelationList

### ISSUE THREAD

**Issue by wiktor-grochal** [VPAC/django-pbs#1]
Hi it seems a model is missing. 
`from django_pbs.servers.models import Server, Node, Queue, RelationList `
and models.py doesn't contain this model at all.

Wiktor

**Comment by brianmay** [comment]
Hello,

Thanks for your report.

Unfortunately, since the [demise of VPAC in December 2015](https://en.wikipedia.org/wiki/Victorian_Partnership_for_Advanced_Computing), this project is basically dead. In fact, I don't appear to have write access anymore.

If you want to resurrect development, and/or submit a pull request to fix the missing import, please let me know. I might be able to get write access back and/or fork this project under the Karaage-Cluster organisation.

As for ``RelationList`` - I have no idea. I would recommend you try searching the git history, in case it was accidentally deleted at some point.

Most likely however this code was never written. As this project doesn't have any unit tests, this was probably forgotten years ago. If somebody really was keen on resurrecting this project, writing good unit tests and integration tests would be a good start. Also testing to ensure it works with Django 1.11 LTS would be a good idea.

Regards

CC @levlafayette who appears to still have owner rights to the VPAC organisation.
